export const EXCLUDED_COUNTRIES = {
  AL: "Albania",
  AO: "Angola",
  BB: "Barbados",
  BW: "Botswana",
  MM: "Myanmar",
  KH: "Cambodia",
  CA: "Canada",
  CU: "Cuba",
  CN: "China",
  KP: "Democratic People's Republic of Korea",
  CD: "Democratic Republic of the Congo",
  EC: "Equador",
  ET: "Ethiopia",
  GH: "Ghana",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  JM: "Jamaica",
  MU: "Mauritius",
  LY: "Libya",
  NI: "Nicaragua",
  PK: "Pakistan",
  PA: "Panama",
  RU: "Russia",
  SO: "Somalia",
  RS: "Serbia",
  LK: "Sri Lanka",
  SS: "South Sudan",
  SD: "Sudan",
  SY: "Syria",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  UG: "Uganda",
  US: "United States",
  YE: "Yemen",
};
