name: Lint and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Yarn Install
        run: |
          yarn install --silent --production=false
      - name: Linting
        run: |
          yarn lint:ci
      - name: Yarn Build
        run: |
          yarn build
